// frontend-vue/src/components/user/shared/LessonSidebar.vue
<template>
  <div class="h-full flex flex-col bg-white dark:bg-gray-900">
    <!-- Header -->
    <div class="p-4 border-b border-gray-200 dark:border-gray-700">
      <h3 class="font-semibold text-gray-800 dark:text-gray-100">Danh sách bài học</h3>
      <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">{{ lessons.length }} bài học</p>
    </div>

    <!-- Lesson List -->
    <div class="flex-1 overflow-y-auto p-3">
      <ul v-if="lessons.length" class="space-y-2">
        <li v-for="(lesson, index) in lessons" :key="lesson.id">
          <button
            class="w-full text-left px-3 py-3 rounded text-sm transition-colors flex items-center gap-3"
            :class="getLessonClass(lesson)"
            :disabled="!lesson.isUnlocked"
            @click="lesson.isUnlocked && $emit('select-lesson', lesson.id)"
          >
            <!-- Number Badge -->
            <div
              class="w-7 h-7 rounded flex items-center justify-center shrink-0 font-medium text-xs"
              :class="getNumberClass(lesson)"
            >
              {{ index + 1 }}
            </div>

            <!-- Title -->
            <span class="truncate flex-1">{{ lesson.title }}</span>

            <!-- Status Icon -->
            <el-icon v-if="lesson.isCompleted" class="text-green-500 shrink-0" :size="18">
              <CircleCheckFilled />
            </el-icon>
            <el-icon v-else-if="!lesson.isUnlocked" class="text-gray-400 shrink-0" :size="16">
              <Lock />
            </el-icon>
          </button>
        </li>
      </ul>

      <div v-else class="flex flex-col items-center justify-center py-12 text-gray-400">
        <el-icon class="is-loading mb-2" :size="28"><Loading /></el-icon>
        <p class="text-xs">Đang tải...</p>
      </div>
    </div>

    <!-- Footer -->
    <div class="p-4 border-t border-gray-200 dark:border-gray-700">
      <div class="flex items-center justify-between text-xs">
        <span class="text-gray-600 dark:text-gray-400">
          Đã hoàn thành: <strong>{{ completedCount }}/{{ lessons.length }}</strong>
        </span>
        <span class="font-semibold text-blue-600 dark:text-blue-400"> {{ completionRate }}% </span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { CircleCheckFilled, Loading, Lock } from '@element-plus/icons-vue'

const props = defineProps({
  lessons: { type: Array, default: () => [] },
  currentLessonId: { type: [Number, String], default: null },
})

defineEmits(['select-lesson'])

const completedCount = computed(() => props.lessons.filter((l) => l.isCompleted).length)
const completionRate = computed(() => {
  if (props.lessons.length === 0) return 0
  return Math.round((completedCount.value / props.lessons.length) * 100)
})

const getLessonClass = (lesson) => {
  const isActive = lesson.id === props.currentLessonId

  if (isActive) {
    return 'bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 font-medium'
  }

  if (!lesson.isUnlocked) {
    return 'bg-gray-50 dark:bg-gray-800 text-gray-400 cursor-not-allowed'
  }

  if (lesson.isCompleted) {
    return 'hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
  }

  return 'hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
}

const getNumberClass = (lesson) => {
  const isActive = lesson.id === props.currentLessonId

  if (isActive) {
    return 'bg-blue-600 text-white'
  }

  if (!lesson.isUnlocked) {
    return 'bg-gray-200 dark:bg-gray-700 text-gray-400'
  }

  if (lesson.isCompleted) {
    return 'bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400'
  }

  return 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400'
}
</script>

<style scoped>
/* Minimalist scrollbar */
div::-webkit-scrollbar {
  width: 4px;
}

div::-webkit-scrollbar-track {
  background: transparent;
}

div::-webkit-scrollbar-thumb {
  background: #d1d5db;
  border-radius: 2px;
}

div::-webkit-scrollbar-thumb:hover {
  background: #9ca3af;
}

html.dark div::-webkit-scrollbar-thumb {
  background: #4b5563;
}

html.dark div::-webkit-scrollbar-thumb:hover {
  background: #6b7280;
}
</style>

// frontend/src/components/grammar/sidebar/LessonSidebar.jsx
import React from 'react';
import {
  Card,
  Typography,
  List,
  ListItem,
  ListItemPrefix,
  Accordion,
  AccordionHeader,
  AccordionBody,
  Progress,
  Chip,
} from "@material-tailwind/react";
import {
  ChevronDownIcon,
  ChevronRightIcon,
  LockClosedIcon,
  CheckCircleIcon,
  DocumentTextIcon,
  PlayCircleIcon,
} from '@heroicons/react/24/outline';

const LessonSidebar = ({ 
  topics = [],
  currentTopic,
  currentLesson, 
  expandedTopics = [],
  onToggleTopic, 
  onSelectLesson 
}) => {{ topics, currentTopic, expandedTopics };

  return (
    <Card className="h-full rounded-none shadow-xl card-base flex flex-col overflow-hidden">
      {/* Header */}
      <div className="p-4 border-b border-primary flex-shrink-0">
        <Typography variant="h6" className="font-bold text-primary">
          Danh sách bài học
        </Typography>
        {currentTopic && (
          <div className="mt-3">
            <div className="flex justify-between mb-2">
              <Typography variant="small" className="text-secondary">
                Tiến độ:
              </Typography>
              <Typography variant="small" className="font-medium text-primary">
                {currentTopic.completedLessons || 0}/{currentTopic.totalLessons || 0}
              </Typography>
            </div>
            <Progress 
              value={currentTopic.totalLessons > 0 
                ? ((currentTopic.completedLessons || 0) / currentTopic.totalLessons) * 100 
                : 0}
              color="green"
              className="h-2"
            />
          </div>
        )}
      </div>

      {/* Topics List */}
      <div className="flex-1 overflow-y-auto">
        {topics && topics.length > 0 ? (
          topics.map((topic) => {
            const isExpanded = expandedTopics.includes(topic.id);
            const lessons = topic.lessons || [];
            
            return (
              <Accordion
                key={topic.id}
                open={isExpanded}
                animate={{
                  mount: { scale: 1 },
                  unmount: { scale: 0.95 },
                }}
                className="border-b border-primary"
              >
                <AccordionHeader
                  onClick={() => onToggleTopic(topic.id)}
                  className="border-b-0 p-4 hover:bg-tertiary transition-colors"
                >
                  <div className="flex items-center justify-between w-full">
                    <div className="flex-1 min-w-0">
                      <Typography variant="small" className="font-semibold text-primary truncate">
                        {topic.name}
                      </Typography>
                      <Typography variant="small" className="text-secondary text-xs mt-1">
                        {topic.completedLessons || 0}/{topic.totalLessons || 0} bài
                      </Typography>
                    </div>
                    {isExpanded ? (
                      <ChevronDownIcon className="h-4 w-4 text-secondary ml-2 flex-shrink-0" />
                    ) : (
                      <ChevronRightIcon className="h-4 w-4 text-secondary ml-2 flex-shrink-0" />
                    )}
                  </div>
                </AccordionHeader>

                <AccordionBody className="py-0">
                  {/* ✅ Always render List with content */}
                  <div className="bg-tertiary">
                    {lessons.length > 0 ? (
                      <List className="p-0">
                        {lessons.map((lesson, index) => {
                          const isActive = currentLesson?.id === lesson.id;
                          const isLocked = !lesson.isUnlocked;

                          return (
                            <ListItem
                              key={lesson.id}
                              onClick={() => !isLocked && onSelectLesson(lesson.id, lesson.isUnlocked)}
                              className={`p-3 pl-6 ${
                                isActive 
                                  ? 'bg-blue-50 dark:bg-blue-900/30 border-l-4 border-blue-500' 
                                  : isLocked
                                  ? 'opacity-50 cursor-not-allowed'
                                  : 'hover:bg-secondary cursor-pointer'
                              }`}
                            >
                              <ListItemPrefix className="mr-3">
                                {isLocked ? (
                                  <LockClosedIcon className="h-5 w-5 text-gray-400" />
                                ) : lesson.isCompleted ? (
                                  <CheckCircleIcon className="h-5 w-5 text-green-500" />
                                ) : lesson.lessonType === 'THEORY' ? (
                                  <DocumentTextIcon className="h-5 w-5 text-blue-500" />
                                ) : (
                                  <PlayCircleIcon className="h-5 w-5 text-green-500" />
                                )}
                              </ListItemPrefix>

                              <div className="flex-1 min-w-0">
                                <Typography
                                  variant="small"
                                  className={`font-medium truncate ${
                                    isActive ? 'text-blue-600 dark:text-blue-400' : 'text-primary'
                                  }`}
                                >
                                  {index + 1}. {lesson.title}
                                </Typography>
                                
                                <div className="flex items-center gap-2 mt-1 flex-wrap">
                                  <Chip
                                    size="sm"
                                    value={lesson.lessonType === 'THEORY' ? 'Lý thuyết' : 'Thực hành'}
                                    className={`text-xs ${
                                      lesson.lessonType === 'THEORY'
                                        ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300'
                                        : 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300'
                                    }`}
                                  />

                                  {lesson.estimatedDuration && (
                                    <Typography variant="small" className="text-secondary text-xs">
                                      {Math.ceil(lesson.estimatedDuration / 60)}p
                                    </Typography>
                                  )}

                                  {lesson.isCompleted && lesson.userScore > 0 && (
                                    <Typography variant="small" className="text-green-600 dark:text-green-400 font-medium text-xs">
                                      {lesson.userScore}%
                                    </Typography>
                                  )}
                                </div>
                              </div>
                            </ListItem>
                          );
                        })}
                      </List>
                    ) : (
                      <div className="p-4 text-center">
                        <Typography variant="small" className="text-secondary">
                          Chưa có bài học
                        </Typography>
                      </div>
                    )}
                  </div>
                </AccordionBody>
              </Accordion>
            );
          })
        ) : (
          <div className="p-8 text-center">
            <Typography variant="small" className="text-secondary">
              Đang tải danh sách bài học...
            </Typography>
          </div>
        )}
      </div>
    </Card>
  );
};

export default LessonSidebar;
